### ISSUE TITLE
No eligible build target.

### ISSUE THREAD

**Issue by drjehr** [idleberg/atom-build-tsc#1]
I get the following error when trying to build a typescript project.
```
No eligible build target.
No configuration to build this project exists.
```
The project contains a `tsconfig.json` file in root folder which I believe should be fine?

**Comment by idleberg** [comment]
Is `tsc` in your PATH?

**Comment by drjehr** [comment]
No, does it have to be?
The readme doesn't mention any dependencies or requirements.

**Comment by idleberg** [comment]
Yes, it needs to be in your PATH, otherwise this package cannot find it. I probably expected this to be common knowledge, but you're right – it wouldn't hurt to mention this in the readme.

Until now I never considered installing `tsc` as a Node dependency, but it could be done (unless the [`build`](https://github.com/noseglid/atom-build) package has problems with it). However, I think the current implementation is better, since you stay in control of which version of `tsc` to use.

**Comment by drjehr** [comment]
Thanks for the reply and clarification. 
I think it very common, as a developer, to expect some things to be common knowledge. I do have the same approach myself but I when I started learning coding I often felt it was a black box full of things I was supposed to know, but no one told me. A friend of mine is at that stage now and I recognise his frustration.
I think everybody knows this more or less, e.g. when learning some new program and the documentation for it is poor, obsolete or missing. ;-)

Getting back on topic, the [`atom-typescript`](https://atom.io/packages/atom-typescript) package can also build, but without `tsc` in PATH. So I guess pointing out the dependency is very helpful.

**Comment by drjehr** [comment]
Or... the error message could point out that `tsc` is needed in PATH. :-)

**Comment by idleberg** [comment]
> Or... the error message could point out that tsc is needed in PATH. :-)

All eligibility errors are coming from the main [`build`](https://github.com/noseglid/atom-build) package and cannot be changed. I remember when I started using build providers, I found this very frustrating myself.

**Comment by drjehr** [comment]
Ah yeah ok. That's pretty much a major flaw as build providers has no method of helping users then.

**Comment by drjehr** [comment]
You can close this if you want to. :-)
